# Project identification
sonar.projectKey=Recipeasy
sonar.projectName=Recipeasy
sonar.projectVersion=1.0

# Source and Test folders
sonar.sources=lib/
sonar.tests=test/

# Important: Tell Sonar which files are test files
sonar.test.inclusions=test/**/*.dart

# Excluded files
sonar.exclusions=**/*.apk,**/*.bin,**/*.dill,**/*.so

# Encoding
sonar.sourceEncoding=UTF-8

sonar.dart.analysis.restoreOriginalAnalysisOptions=false