// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU1OhOlC6CYnbEHiFV4U79M-a020qZHCQ',
    appId: '1:689644491138:web:a3ad4aafa50ae9b06e3f9b',
    messagingSenderId: '689644491138',
    projectId: 'recipeasy-d55e8',
    authDomain: 'recipeasy-d55e8.firebaseapp.com',
    storageBucket: 'recipeasy-d55e8.firebasestorage.app',
    measurementId: 'G-7R9J8GMHBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF9vIvi9PCPvMaoYszrf1KQiNvSDQNZlg',
    appId: '1:689644491138:android:cb109edf48f7740f6e3f9b',
    messagingSenderId: '689644491138',
    projectId: 'recipeasy-d55e8',
    storageBucket: 'recipeasy-d55e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtdDEvoEk-Ez3uPlNyzQQXHVytJHf02zA',
    appId: '1:689644491138:ios:8996ddd1076ea3fd6e3f9b',
    messagingSenderId: '689644491138',
    projectId: 'recipeasy-d55e8',
    storageBucket: 'recipeasy-d55e8.firebasestorage.app',
    iosBundleId: 'com.fariselbaz.recipeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtdDEvoEk-Ez3uPlNyzQQXHVytJHf02zA',
    appId: '1:689644491138:ios:b94e25bf191da3a56e3f9b',
    messagingSenderId: '689644491138',
    projectId: 'recipeasy-d55e8',
    storageBucket: 'recipeasy-d55e8.firebasestorage.app',
    iosBundleId: 'com.example.recipeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU1OhOlC6CYnbEHiFV4U79M-a020qZHCQ',
    appId: '1:689644491138:web:54b38bf41103c67a6e3f9b',
    messagingSenderId: '689644491138',
    projectId: 'recipeasy-d55e8',
    authDomain: 'recipeasy-d55e8.firebaseapp.com',
    storageBucket: 'recipeasy-d55e8.firebasestorage.app',
    measurementId: 'G-62D5T0Q6YR',
  );
}
